/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

/**
 *
 * @author ACER
 */
public class DialogCargando extends javax.swing.JDialog {

    /**
     * Creates new form DialogCargando
     */
    FrameLogin frmLogin;
    DialogProducto dp;
    DialogUsuarios du;
    DialogAgregarUsuario dau;
    DialogClientes dcli;
    DialogAgregarProducto dap;
    DialogAgregarCliente dacli;
    DialogMascotas dm;
    DialogAgregarMascota dam;
    DialogHistorialVentas dhv;
    DialogAgenda da;
    DialogAgregarAgenda daa;
    String pantalla;
    public DialogCargando(java.awt.Frame parent, boolean modal,String pantalla) {
        super(parent, modal);
        initComponents();
        this.pantalla= pantalla;
        switch(this.pantalla){
            case "login": 
                 frmLogin= (FrameLogin) parent;
                break;
        }
       
    }
    public DialogCargando(java.awt.Dialog parent, boolean modal, String pantalla) {
        super(parent, modal);
        initComponents();
        this.pantalla = pantalla;
        switch (this.pantalla) {
            case "productos":
                 lblMensaje.setText("Cargando Productos...");
                dp = (DialogProducto) parent;
                break;
            case "usuarios":
                 lblMensaje.setText("Cargando Usuarios...");
                du = (DialogUsuarios) parent;
                break;
            case "clientes":
                 lblMensaje.setText("Cargando Clientes...");
                dcli = (DialogClientes) parent;
                break;
            case "mascotas":
                 lblMensaje.setText("Cargando Mascotas...");
                dm = (DialogMascotas) parent;
                break;
            case "agenda":
                lblMensaje.setText("Cargando Registros...");
                da= (DialogAgenda) parent;
                break;
            case "agregarProducto":
                lblMensaje.setText("Agregando Producto...");
                dap = (DialogAgregarProducto) parent;
                break;
            case "editarProducto":
                lblMensaje.setText("Actualizando Datos Del Producto...");
                dap = (DialogAgregarProducto) parent;
                break;
            case "agregarCliente":
                lblMensaje.setText("Agregando Cliente...");
                dacli = (DialogAgregarCliente) parent;
                break;
            case "editarCliente":
                lblMensaje.setText("Actualizando Datos Del Cliente...");
                dacli = (DialogAgregarCliente) parent;
                break;
            case "agregarMascota":
                lblMensaje.setText("Agregando Mascota...");
                dam = (DialogAgregarMascota) parent;
                break;
            case "editarMascota":
                lblMensaje.setText("Actualizando Datos De La Mascota...");
                dam = (DialogAgregarMascota) parent;
                break;
            case "agregarUsuario":
                lblMensaje.setText("Agregando Usuario...");
                dau = (DialogAgregarUsuario) parent;
                break;
            case "historial": 
                lblMensaje.setText("Cargando Ventas...");
                dhv=(DialogHistorialVentas)parent;
                break;
            case "agregarAgenda": 
                lblMensaje.setText(" Guardando Agenda...");
               daa=(DialogAgregarAgenda)parent;
                break;
            case "editarAgenda": 
                lblMensaje.setText(" Actualizando Fecha...");
               daa=(DialogAgregarAgenda)parent;
                break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setText("Cargando...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMensaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblMensaje)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         switch(this.pantalla){
            case "login": 
                 frmLogin.entrar();
                break;
            case "productos":
                try{
                dp.desplegarRegistros();
                }catch(Exception e){
                this.dispose();
                }
                break;
            case "usuarios":
                try{
                du.desplegarRegistros();
                }catch(Exception e){
                this.dispose();
                }
                
               break;
            case "clientes":
                try{
                dcli.desplegarRegistros();
                }catch(Exception e){
                this.dispose();
                }
                
                break;
            case "agenda":
                try{
                da.desplegarRegistros();
                }catch(Exception e){
                this.dispose();
                }
                
                break;
            case "agregarProducto":
                dap.cargar();
                break;
            case"editarProducto":
                dap.actualizar();
               break;
            case "agregarCliente":
                dacli.cargar();
                break;
            case "editarCliente":
                dacli.actualizar();
                break;
            case "mascotas":
                try{
                dm.desplegarRegistros();
                }catch(Exception e){
                this.dispose();
                }
                break;
            case "agregarMascota":
                dam.cargar();
                break;
            case "editarMascota":
                dam.actualizar();
                break;
            case "agregarUsuario":
                dau.cargar();
                break;
            case "historial":
                try{
                dhv.desplegarRegistros();
                }catch(Exception e){
                this.dispose();
                }
                break;
            case "agregarAgenda": 
                daa.cargar();
                break;
            case "editarAgenda": 
                daa.actualizar();
                break;
            
                
        }
        
        dispose();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogCargando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogCargando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogCargando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogCargando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogCargando dialog = new DialogCargando(new javax.swing.JFrame(), true,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMensaje;
    // End of variables declaration//GEN-END:variables
}
