/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import SQL.Sentencias;
import javax.swing.JFrame;

/**
 *
 * @author msi gs63
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal2
     */
    private int id_sesion;
    public FramePrincipal( int id_sesion) {
        initComponents();
        this.id_sesion= id_sesion;
        jLabel1.setText(this.id_sesion+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtoolBarPrincipal = new javax.swing.JToolBar();
        jbtnNuevo = new javax.swing.JButton();
        jbtnNuevo1 = new javax.swing.JButton();
        jbtnNuevo2 = new javax.swing.JButton();
        jbtnNuevo3 = new javax.swing.JButton();
        jbtnNuevo4 = new javax.swing.JButton();
        jscrollPanePrincipal = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jbtnVenta = new javax.swing.JButton();
        jbtnClientes = new javax.swing.JButton();
        jbtnMascotas = new javax.swing.JButton();
        jbtnProducto = new javax.swing.JButton();
        jbtnUsuarios = new javax.swing.JButton();
        jbtnAgenda = new javax.swing.JButton();
        jbtnAgenda1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jtoolBarPrincipal.setFloatable(false);
        jtoolBarPrincipal.setRollover(true);
        jtoolBarPrincipal.setFocusable(false);
        jtoolBarPrincipal.setRequestFocusEnabled(false);

        jbtnNuevo.setText("Nuevo");
        jtoolBarPrincipal.add(jbtnNuevo);

        jbtnNuevo1.setText("Editar");
        jbtnNuevo1.setFocusable(false);
        jbtnNuevo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNuevo1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolBarPrincipal.add(jbtnNuevo1);

        jbtnNuevo2.setText("Eliminar");
        jbtnNuevo2.setFocusable(false);
        jbtnNuevo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNuevo2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolBarPrincipal.add(jbtnNuevo2);

        jbtnNuevo3.setText("Inicio");
        jbtnNuevo3.setFocusable(false);
        jbtnNuevo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNuevo3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolBarPrincipal.add(jbtnNuevo3);

        jbtnNuevo4.setText("Filtrar");
        jbtnNuevo4.setFocusable(false);
        jbtnNuevo4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNuevo4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolBarPrincipal.add(jbtnNuevo4);

        jbtnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Venta_icon.png"))); // NOI18N
        jbtnVenta.setText(" ");
        jbtnVenta.setMaximumSize(new java.awt.Dimension(85, 60));
        jbtnVenta.setPreferredSize(new java.awt.Dimension(85, 60));
        jbtnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVentaActionPerformed(evt);
            }
        });

        jbtnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cliente_icon.png"))); // NOI18N
        jbtnClientes.setText(" ");
        jbtnClientes.setMaximumSize(new java.awt.Dimension(85, 60));
        jbtnClientes.setPreferredSize(new java.awt.Dimension(85, 60));
        jbtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClientesActionPerformed(evt);
            }
        });

        jbtnMascotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/huella_icon.png"))); // NOI18N
        jbtnMascotas.setText(" ");
        jbtnMascotas.setMaximumSize(new java.awt.Dimension(85, 60));
        jbtnMascotas.setPreferredSize(new java.awt.Dimension(85, 60));
        jbtnMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMascotasActionPerformed(evt);
            }
        });

        jbtnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orden_icon.png"))); // NOI18N
        jbtnProducto.setText(" ");
        jbtnProducto.setMaximumSize(new java.awt.Dimension(85, 60));
        jbtnProducto.setPreferredSize(new java.awt.Dimension(85, 60));
        jbtnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProductoActionPerformed(evt);
            }
        });

        jbtnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Usuarios_icon.png"))); // NOI18N
        jbtnUsuarios.setText(" ");
        jbtnUsuarios.setMaximumSize(new java.awt.Dimension(85, 60));
        jbtnUsuarios.setPreferredSize(new java.awt.Dimension(85, 60));
        jbtnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUsuariosActionPerformed(evt);
            }
        });

        jbtnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agenda.png"))); // NOI18N
        jbtnAgenda.setText(" ");
        jbtnAgenda.setMaximumSize(new java.awt.Dimension(85, 60));
        jbtnAgenda.setPreferredSize(new java.awt.Dimension(85, 60));
        jbtnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgendaActionPerformed(evt);
            }
        });

        jbtnAgenda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Historial_Venta.png"))); // NOI18N
        jbtnAgenda1.setText(" ");
        jbtnAgenda1.setMaximumSize(new java.awt.Dimension(85, 60));
        jbtnAgenda1.setPreferredSize(new java.awt.Dimension(85, 60));
        jbtnAgenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgenda1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtnAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jbtnClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnMascotas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jbtnAgenda1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnMascotas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jbtnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnAgenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jscrollPanePrincipal.setViewportView(jPanel1);

        jLabel1.setText("jLabel1");

        jMenu1.setText("File");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jscrollPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(833, 833, 833))
                    .addComponent(jtoolBarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtoolBarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jscrollPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVentaActionPerformed
        DialogVentas dialogVentas = new DialogVentas( this, false);
        dialogVentas.setVisible( true );
    }//GEN-LAST:event_jbtnVentaActionPerformed

    private void jbtnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnProductoActionPerformed

    private void jbtnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgendaActionPerformed

    private void jbtnAgenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgenda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgenda1ActionPerformed

    private void jbtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClientesActionPerformed
        DialogClientes dialogClientes = new DialogClientes( this, false );
        dialogClientes.setVisible( true );
    }//GEN-LAST:event_jbtnClientesActionPerformed

    private void jbtnMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMascotasActionPerformed
        DialogMascotas dialogMascotas = new DialogMascotas( this, false);
        dialogMascotas.setVisible( true );
    }//GEN-LAST:event_jbtnMascotasActionPerformed

    private void jbtnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnUsuariosActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Sentencias.cerrarSesion(id_sesion, Sentencias.getFechaHora());
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnAgenda;
    private javax.swing.JButton jbtnAgenda1;
    private javax.swing.JButton jbtnClientes;
    private javax.swing.JButton jbtnMascotas;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JButton jbtnNuevo1;
    private javax.swing.JButton jbtnNuevo2;
    private javax.swing.JButton jbtnNuevo3;
    private javax.swing.JButton jbtnNuevo4;
    private javax.swing.JButton jbtnProducto;
    private javax.swing.JButton jbtnUsuarios;
    private javax.swing.JButton jbtnVenta;
    private javax.swing.JScrollPane jscrollPanePrincipal;
    private javax.swing.JToolBar jtoolBarPrincipal;
    // End of variables declaration//GEN-END:variables
}
