/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import SQL.Sentencias;
import javax.swing.JFrame;

/**
 *
 * @author msi gs63
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal2
     */
    private int id_sesion;
    public FramePrincipal( int id_sesion) {
        initComponents();
        this.id_sesion= id_sesion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jscrollPanePrincipal = new javax.swing.JScrollPane();
        jbtnVenta = new javax.swing.JButton();
        jbtnClientes = new javax.swing.JButton();
        jbtnMascotas = new javax.swing.JButton();
        jbtnUsuarios = new javax.swing.JButton();
        jbtnProducto = new javax.swing.JButton();
        jbtnAgenda = new javax.swing.JButton();
        jbtnAgenda1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jbtnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Venta_icon.png"))); // NOI18N
        jbtnVenta.setText(" ");
        jbtnVenta.setMaximumSize(new java.awt.Dimension(85, 60));
        jbtnVenta.setPreferredSize(new java.awt.Dimension(85, 60));
        jbtnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVentaActionPerformed(evt);
            }
        });

        jbtnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cliente_icon.png"))); // NOI18N
        jbtnClientes.setText(" ");
        jbtnClientes.setMaximumSize(new java.awt.Dimension(85, 60));
        jbtnClientes.setPreferredSize(new java.awt.Dimension(85, 60));
        jbtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClientesActionPerformed(evt);
            }
        });

        jbtnMascotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/huella_icon.png"))); // NOI18N
        jbtnMascotas.setText(" ");
        jbtnMascotas.setMaximumSize(new java.awt.Dimension(85, 60));
        jbtnMascotas.setPreferredSize(new java.awt.Dimension(85, 60));
        jbtnMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMascotasActionPerformed(evt);
            }
        });

        jbtnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Usuarios_icon.png"))); // NOI18N
        jbtnUsuarios.setText(" ");
        jbtnUsuarios.setMaximumSize(new java.awt.Dimension(85, 60));
        jbtnUsuarios.setPreferredSize(new java.awt.Dimension(85, 60));
        jbtnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUsuariosActionPerformed(evt);
            }
        });

        jbtnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orden_icon.png"))); // NOI18N
        jbtnProducto.setText(" ");
        jbtnProducto.setMaximumSize(new java.awt.Dimension(85, 60));
        jbtnProducto.setPreferredSize(new java.awt.Dimension(85, 60));
        jbtnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProductoActionPerformed(evt);
            }
        });

        jbtnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agenda.png"))); // NOI18N
        jbtnAgenda.setText(" ");
        jbtnAgenda.setMaximumSize(new java.awt.Dimension(85, 60));
        jbtnAgenda.setPreferredSize(new java.awt.Dimension(85, 60));
        jbtnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgendaActionPerformed(evt);
            }
        });

        jbtnAgenda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        jbtnAgenda1.setText(" ");
        jbtnAgenda1.setMaximumSize(new java.awt.Dimension(85, 60));
        jbtnAgenda1.setPreferredSize(new java.awt.Dimension(85, 60));
        jbtnAgenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgenda1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jscrollPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtnAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                            .addComponent(jbtnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnMascotas, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnAgenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jbtnVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(jbtnMascotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnAgenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jscrollPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(jbtnProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVentaActionPerformed
        DialogVentas dialogVentas = new DialogVentas( this, false);
        dialogVentas.setVisible( true );
    }//GEN-LAST:event_jbtnVentaActionPerformed

    private void jbtnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProductoActionPerformed
        DialogProducto dialogProducto = new DialogProducto( this, true );
        dialogProducto.setVisible( true );
    }//GEN-LAST:event_jbtnProductoActionPerformed

    private void jbtnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgendaActionPerformed
        DialogAgenda dialogAgenda = new DialogAgenda( this, true );
        dialogAgenda.setVisible( true );
        
    }//GEN-LAST:event_jbtnAgendaActionPerformed

    private void jbtnAgenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgenda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgenda1ActionPerformed

    private void jbtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClientesActionPerformed
        DialogClientes dialogClientes = new DialogClientes( this, false );
        dialogClientes.setVisible( true );
    }//GEN-LAST:event_jbtnClientesActionPerformed

    private void jbtnMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMascotasActionPerformed
        DialogMascotas dialogMascotas = new DialogMascotas( this, false);
        dialogMascotas.setVisible( true );
    }//GEN-LAST:event_jbtnMascotasActionPerformed

    private void jbtnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUsuariosActionPerformed
        DialogUsuarios dialogUsuarios = new DialogUsuarios( this, true );
        dialogUsuarios.setVisible( true );
    }//GEN-LAST:event_jbtnUsuariosActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Sentencias.cerrarSesion(id_sesion, Sentencias.getFechaHora());
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton jbtnAgenda;
    private javax.swing.JButton jbtnAgenda1;
    private javax.swing.JButton jbtnClientes;
    private javax.swing.JButton jbtnMascotas;
    private javax.swing.JButton jbtnProducto;
    private javax.swing.JButton jbtnUsuarios;
    private javax.swing.JButton jbtnVenta;
    private javax.swing.JScrollPane jscrollPanePrincipal;
    // End of variables declaration//GEN-END:variables
}
